version: "3"
services:
  haproxy:
    image: eea-haproxy:1.8.22
    depends_on:
    - webapp
    ports:
    - "81:8080"
    - "1936:1936"
    environment:
      FRONTEND_PORT: "8080"
      BACKENDS: "webapp"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"
      HTTPCHK: "GET /"
      INTER: "5s"
      LOG_LEVEL: "info"
  webapp:
    image: simple-web:1.0
    environment:
      PORT: "8080"
